### ISSUE TITLE
NameError: name 'AverageAttention' is not defined

### ISSUE THREAD

**Issue by X-F-Cui** [chenweize1998/fully-hyperbolic-nn#1]
Hi,

When I'm trying to run the evaluation step using the command 
`bash eval_iwslt.sh 4 0 ~/fully-hyperbolic-nn-main/mt/model/iwslt/64/bs=10240_ac=1_dp=0.0_attdp=0.1_gn=0.5_ws=6000_lr=5/model_step_40000.pt`
This error message comes up: 
`NameError: name 'AverageAttention' is not defined`
I'm wondering where AverageAttention was first defined and imported. Thank you so much!

**Comment by chenweize1998** [comment]
Sorry for the bug. Try to delete the code https://github.com/chenweize1998/fully-hyperbolic-nn/blob/1d3cb8cdaa74f480d6dd7b06f2d64ae41f934fe5/mt/onmt/decoders/ltransformer.py#L362-L365
and adjust the indentation, see whether the error is still there. `AverageAttention` is an unused module, it's just that I forgot to delete the references when I was cleaning the code.
