### ISSUE TITLE
 squared Lorentzian distance in code and paper

### ISSUE THREAD

**Issue by sijia1999** [chenweize1998/fully-hyperbolic-nn#2]
May I ask why squared Lorentzian distance is -2/k-2<a,b> in the code instead of 2/k-2<a,b> in the paper
![1648107761(1)](https://user-images.githubusercontent.com/75306158/159866835-1db8b901-6b47-4d1e-87cd-0d83ec2818eb.png)
![1648107796(1)](https://user-images.githubusercontent.com/75306158/159866871-49294ace-b87d-4491-9d96-b5ea540b16c5.png)

**Comment by chenweize1998** [comment]
The `K` in our paper is the negative curvature, we simply use `K=-1` in our code. And when calculating the weights of attention, a smaller distance should indicate higher similarity. Therefore, we feed the **negative** Lorentzian distance into the softmax function to make similar tokens obtain higher weight.

**Comment by sijia1999** [comment]
Thank you for your answer！

**Comment by sijia1999** [comment]
Hello,   I encountered one problem again while reading the code. May I ask how the scale initialization value is determined and what factors it is related to. If the initialization value is not set properly, will the result of embedding dimension with low dimension such as 8 and high dimension such as 64 be similar?

![捕获](https://user-images.githubusercontent.com/75306158/172291193-dea4a114-b91c-434f-bfd6-ebf9f4613f5d.PNG)

**Comment by chenweize1998** [comment]
`self.scale.exp()` corresponds to the \lambda inside \phi(Wx, v) in equation (3) of the paper. We set it to be approximately 10 empirically (exp(2.3)=9.97). We actually did not do much searching on it. If you encounter any stability problems, you can try to lower the initialization value. 
Generally, a larger dimension will bring better performance, but there's no guarantee that this will always be the case, and it's also largely task-dependent. I can only say that the initialization of this value _could be_ one of the reasons.

**Comment by sijia1999** [comment]
Ok, thank you again for your answer, I will go to further study！
